# 服务配置
server:
    port: 9999

# 英克正式库 默认数据源
spring:
    datasource.db1.jdbc-url: jdbc:oracle:thin:@192.168.1.183:1521:orcl
    datasource.db1.username: zjzjk
    datasource.db1.password: zjzjk
    datasource.db1.driverClassName: oracle.jdbc.driver.OracleDriver
    

# 英克测试库
    datasource.db2.jdbc-url: jdbc:oracle:thin:@192.168.1.183:1521:orcl
    datasource.db2.username: gzddsyf
    datasource.db2.password: gzddsyf
    datasource.db2.driverClassName: oracle.jdbc.driver.OracleDriver
    
    datasource.initialSize: 5
    datasource.minIdle: 5
    datasource.maxActive: 20
    # 配置获取连接等待超时的时间
    datasource.maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    datasource.timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    datasource.minEvictableIdleTimeMillis: 300000
    datasource.validationQuery: SELECT 1 FROM DUAL
    datasource.testWhileIdle: true
    datasource.testOnBorrow: false
    datasource.testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    datasource.filters: stat,wall,log4j
    datasource.logSlowSql: true

# mybatis的配置
mybatis:
    type-aliases-package: com.ak1ak1.pojo
    mapper-locations: classpath:mybatis/*.xml

# 分页助手
pagehelper:
    helper-dialect: oracle
    reasonable: true
    support-methods-arguments: true
    params: 

# 日志输出
logging:
    level:
        com.ak1ak1.mapper: debug